### ISSUE TITLE
Post "https://api.openai.com/v1/completions": context deadline exceeded 

### ISSUE THREAD

**Issue by whitebaby** [tomatocuke/openai#1]
您好，我在程序运行时，经常报错。服务器配置，带宽没有问题，请您帮忙看下，如何解决
Post "https://api.openai.com/v1/completions": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

**Comment by nezhafan** [comment]
> 您好，我在程序运行时，经常报错。服务器配置，带宽没有问题，请您帮忙看下，如何解决 Post "https://api.openai.com/v1/completions": context deadline exceeded (Client.Timeout exceeded while awaiting headers)

微信有最长15s的限制，所以调用openAI的接口设置了超时时间14s，超时就舍弃掉。加我QQ: 772532526
