### ISSUE TITLE
这个是不能联系上下文吗

### ISSUE THREAD

**Issue by golangboy** [tomatocuke/openai#12]
感觉都没有上下文关联，是官网api还不支持么

**Comment by wscjxky** [comment]
> 

https://github.com/wscjxky/openai
已经支持了，你可以查看下pullrequsts

**Comment by golangboy** [comment]
> > 
> 
> https://github.com/wscjxky/openai 已经支持了，你可以查看下pullrequsts

感谢！，已部署

**Comment by nezhafan** [comment]
> 感觉都没有上下文关联，是官网api还不支持么

OpenAI那边是不记录会话数据的，实际做法是，将之前的问答都作为下一次的参数传过去。

这样的问题是，一个会造成大量花费，另外，不能一直累积，无法真正的完全记住。

所以不建议把它作为聊天之类的工具
