### ISSUE TITLE
main.go 建议更改下

### ISSUE THREAD

**Issue by wqw547243068** [tomatocuke/openai#15]
[代码](https://github.com/tomatocuke/openai/blob/abef1b0d0d6d933600fb9ddc9105fc711474f3f1/main.go#L21) 中，建议将POST请求的wx接口重置为/，这样nginx/Caddy代理时不用特殊处理，微信公众号平台也只认顶级路径

```go
r.POST("/wx", handler.ReceiveMsg) // 旧
r.POST("/", handler.ReceiveMsg) // 新
```

**Comment by nezhafan** [comment]
”微信公众号平台也只认顶级路径“ 是指什么？    公众号服务地址是可以设置的嘞
我之前用过 / ，但是有些人总会去手动调用，感到困惑。 所以我改成 /wx 表明这是微信的。

**Comment by wqw547243068** [comment]
> 

caddy代理时，不能带子域名
