### ISSUE TITLE
错误日志看不到

### ISSUE THREAD

**Issue by wqw547243068** [tomatocuke/openai#16]
## 现象

输入：
> 翻译这段话 The venture capital market consists of three major types of venture capital (VC): 
independent venture capital (IVC), government-sponsored venture capital (GVC), and corporate venture capital (CVC).

输出：
- ![image](https://user-images.githubusercontent.com/3257257/224901237-965f5b24-1858-47be-a080-f2891622cf22.png)

服务端后台没有任何日志信息
- log/data.log
- 启动服务时 重定向的文件（&>log.txt）也没有错误信息

而OpenAI接口返回正常, 换其他query也正常
- 
![image](https://user-images.githubusercontent.com/3257257/224902859-82b3315c-2c9a-4046-90e0-3099201b7f79.png)

## 问题

日志打印到哪儿？

**Comment by wqw547243068** [comment]
查出来了，是query里包含不可见特殊字符

```sh
# 故障query
翻译这段话 The venture capital market consists of three major types of venture capital (VC): 
independent venture capital (IVC), government-sponsored venture capital (GVC), and corporate venture capital (CVC).
# 正常query
翻译这段话 The venture capital market consists of three major types of venture capital (VC):
independent venture capital (IVC), government-sponsored venture capital (GVC), and corporate venture capital (CVC).
```

用vim看出来了
- ![image](https://user-images.githubusercontent.com/3257257/224904243-a1ffbff2-6cdf-4109-a7c2-7c9ca995f816.png)

**Comment by nezhafan** [comment]
不好意思，才看到 。 😭
