### ISSUE TITLE
filter.go这个文件报了一个错误，undefined: keywords

### ISSUE THREAD

**Issue by evanerv0079** [tomatocuke/openai#18]
![image](https://user-images.githubusercontent.com/2221407/227852535-f48e3aed-ceb2-45d7-aa29-cc56a8b47acb.png)

3月27日上午更新的，请问啥情况呢。

使用的是vscode的go插件

**Comment by nezhafan** [comment]
啊啊啊啊啊！  我少提交代码了。 已经提交
