### ISSUE TITLE
能回复语音就好了

### ISSUE THREAD

**Issue by gooderek** [tomatocuke/openai#20]
公众号本身是支持语音识别的
![无标3423题](https://user-images.githubusercontent.com/121539344/230109222-e72f0001-5bdc-443b-98a5-cf1db626d707.jpg)
如果能做到这个就更好了
![微信图片_20230405221845](https://user-images.githubusercontent.com/121539344/230109443-dd8159e1-3dff-40ff-9d96-af2f86df7f72.jpg)

**Comment by nezhafan** [comment]
已增加

**Comment by gooderek** [comment]
牛逼呀
