### ISSUE TITLE
改动没有效果

### ISSUE THREAD

**Issue by gooderek** [tomatocuke/openai#21]
我把这句话【回复“继续”以滚动查看】的继续改成了1，对应的继续也改了。但文字过长的时候还是现实【回复“继续”以滚动查看】而不是 【回复“1”以滚动查看】，求教

**Comment by nezhafan** [comment]
没什么魔法。有两处，一处文本，一处判断，都在 `internal/service/openai/openai.go` 里。   如果都改了就看看你是否重新编译之类的问题。

**Comment by gooderek** [comment]
搞定了，谢谢大佬
