### ISSUE TITLE
部署之后没有任何反应呢

### ISSUE THREAD

**Issue by fky1990** [tomatocuke/openai#6]
启动服务，使用 curl 'http://127.0.0.1:8080/test?msg=HelloWorld' 测试一下吧

**Comment by nezhafan** [comment]
> 启动服务，使用 curl 'http://127.0.0.1:8080/test?msg=HelloWorld' 测试一下吧

你用什么部署的，看看报错，看看端口是否被占用了。  我更新了这个项目，可以重新看看。     详细你加我QQ:772532526我帮你看看
