### ISSUE TITLE
文件缺失，无法执行

### ISSUE THREAD

**Issue by wqw547243068** [tomatocuke/openai#7]
错误信息：
> internal/handler/user.go:9:2: package openai/internal/service/openai is not in GOROOT (/usr/local/go/src/openai/internal/service/openai)

openai/internal/service/openai  这个文件缺失了。。。

**Comment by nezhafan** [comment]
> 错误信息：
> 
> > internal/handler/user.go:9:2: package openai/internal/service/openai is not in GOROOT (/usr/local/go/src/openai/internal/service/openai)
> 
> openai/internal/service/openai 这个文件缺失了。。。

不好意思，才看到。    那个版本我改动名字造成了文件忽略。    后来已经修复
