### ISSUE TITLE
服务频繁出错

### ISSUE THREAD

**Issue by wqw547243068** [tomatocuke/openai#8]
后台日志频繁出现两类错误：
>- 此接口为公众号验证访问，公众号接入校验失败
>- The server had an error while processing your request. Sorry about that!

错误分析：
- 微信签名验证失败？频率很高
- openai返回的服务错误，然而，单独用chatgpt请求正常(超时问题)

**Comment by nezhafan** [comment]
> 后台日志频繁出现两类错误：
> 
> > * 此接口为公众号验证访问，公众号接入校验失败
> > * The server had an error while processing your request. Sorry about that!
> 
> 错误分析：
> 
> * 微信签名验证失败？频率很高
> * openai返回的服务错误，然而，单独用chatgpt请求正常(超时问题)


1. 微信签名失败。这个大概是你手动调用接口导致的。   因为这个接口是专门给公众号验证的，需要参数，你直接调用这个接口(路由是/，也就是域名/) 是会打印微信签名失败的。
2.  openai的确偶尔会不稳定。  这并非网络造成的，它有几种错误，偶现，并不是一直会这样。  这个可能在代码里重试一下会好一些
